<?php

namespace AppBundle\Repository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends AbstractRepositoryBase implements PriceRepositoryInterface
{

    /**
     * @param int $productId
     * @param int $zoneId
     * @param \AppBundle\ValueObject\Price $priceVo
     * @return \AppBundle\Dto\Price
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     * @throws \Exception
     */
    public function createPrice(int $productId, int $zoneId, \AppBundle\ValueObject\Price $priceVo): \AppBundle\Dto\Price
    {
        $price = new \AppBundle\Entity\Price();
        $price->setValue($priceVo->value);
        $price->setValidFrom($priceVo->validFrom);
        $price->setValidTo($priceVo->validTo);

        $price->setCurrencyZone($this->getEntityManager()->getReference(\AppBundle\Entity\CurrencyZone::class, (int) $zoneId));
        $price->setProduct($this->getEntityManager()->getReference(\AppBundle\Entity\Product::class, (int) $productId));

        $this->validateEntity($price);

        $this->getEntityManager()->persist($price);
        $this->getEntityManager()->flush();

        return $this->getMapperService()->convert($price, \AppBundle\Dto\Price::class);
    }
}
