# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
         FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            methods: [GET, POST, PUT, DELETE]
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

        apiOptions:
            pattern: ^/
            methods: [OPTIONS]
            security: false
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

            # anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
          - { path: ^/api/product, role: ROLE_ADMIN, methods: [PUT, POST, PATCH, DELETE] }
          - { path: ^/api/product, role: ROLE_USER, methods: [GET] }
          - { path: ^/api/zone, role: ROLE_ADMIN, methods: [PUT, POST, PATCH] }
#          - { path: ^/api/user/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }